# Generated by Django 4.1.3 on 2022-12-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_periodicmeasurements_delete_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicmeasurements',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='periodicmeasurements',
            name='pressure',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
