# Generated by Django 4.1.3 on 2023-01-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_humidity_pressure_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidity',
            old_name='humidity',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='pressure',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temperature',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='humidity',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='pressure',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='dateTime',
        ),
    ]
