# Generated by Django 4.1.3 on 2023-01-15 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_rename_humidity_humidity_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidity',
            old_name='value',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='pressure',
            old_name='value',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='value',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='humidity',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
